LAYOUT_WIDTH = 3508
LAYOUT_HEIGHT = 2480
LAYOUT_PADDING_H = 170
LAYOUT_PADDING_V = 230
LAYOUT_BACKGROUND = 'assets/bg.png'

FOLDER_PATH = '../'

BLOCK_MARGIN = 16
BLOCK_WIDTH = 575
BLOCK_HEIGHT = 279

IMAGE_TEXT_MARGIN = 16
IMAGE_TEXT_RESOLUTION = [1, 2]

TEXT_MARGIN = 6
NAME_LINES = 4
SIRE_SIZE = 25
ENUM_SIZE = 25
NAME_SIZE = 30
DESC_SIZE = 23
NUMERATOR_SIZE = 50
WEIGHT_SIZE = 80

PRIMARY_FONT = 'arial.ttf'
SECOND_FONT = 'assets/Lobster.ttf'